# This file was generated by GoReleaser. DO NOT EDIT.
cask "ttl" do
  name "ttl"
  desc "E2E Encrypted Ephemeral Storage"
  homepage "https://ttl.space"
  version "1.0.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ttl"

  on_macos do
    url "https://github.com/tweenietomatoes/ttl/releases/download/v#{version}/ttl_#{version}_darwin_all.tar.gz"
    sha256 "6d1fb706bb0e16d295b4a61b76d00d82cc50f1c7da7f30efa5f0bc20b37167bc"
  end

  on_linux do
    on_intel do
      url "https://github.com/tweenietomatoes/ttl/releases/download/v#{version}/ttl_#{version}_linux_amd64.tar.gz"
      sha256 "a3771bd69fd62e1e7584ff9bf08973b33225abbf11297aac47f43fbc1e72d2ab"
    end
    on_arm do
      url "https://github.com/tweenietomatoes/ttl/releases/download/v#{version}/ttl_#{version}_linux_arm64.tar.gz"
      sha256 "a741a03af94f4a5821520e5804aed2f3fcbb2209a79f5ad5477d46a07a2a676b"
    end
  end

  # No zap stanza required
end
